# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:18080/todo/history
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 5,
  "approvalItem": "",
  "approvalId": "",
  "approvalType": "数据质量",
  "activitiState": "审核不通过",
  "userName": "",
  "userId": "U001",
  "startTime": "",
  "endTime": ""
}

###

POST http://localhost:18080/msg/sendEmail
Content-Type: application/json

{
  "sendEmail": "786470371@qq.com",
  "receiveEmails": [
    "786470371@qq.com"
  ],
  "theme": "主数据发布通知",
  "url": "http://192.168.2.68:9107/",
  "themeChanges": [
    {"name": "**机构","type": "新增", "desc": "用于描述与内部机构信息相关的，由外部权威机构或银行内部发布的，用于全行共享以满足银行规范管理内部机构信息的代码或数据集合","dept": "部门名称","date": "2020-06-19"},
    {"name": "**机构","type": "新增", "desc": "用于描述与内部机构信息相关的，由外部权威机构或银行内部发布的，用于全行共享以满足银行规范管理内部机构信息的代码或数据集合","dept": "部门名称","date": "2020-06-19"}
  ],
  "structureChanges": [
    {"name": "**产品","type": "字段修改","before": "字段【产品适用货币】","after": "字段【产品适用货币】","date": "2020-06-19"},
    {"name": "**产品","type": "字段修改","before": "字段【产品适用货币】","after": "字段【产品适用货币】","date": "2020-06-19"}
  ],
  "dataChanges": [
    {"name": "**机构","type": "数据修改","before": "机构号【100】金融许可证号【1111】","after": "机构号【100】金融许可证号【2222】","date": "2020-06-19"},
    {"name": "**机构","type": "数据修改","before": "机构号【100】金融许可证号【1111】","after": "机构号【100】金融许可证号【2222】","date": "2020-06-19"}
  ]
}

###